hero
anakovalchuk/project-group-11 pull request #5
Opened 2024-09-07 09:02 UTC by OlegSereda898

2024-09-07 10:11 UTC, anakovalchuk requested changes
<img width="251" alt="Screenshot 2024-09-07 at 12 08 26" src="https://github.com/user-attachments/assets/0d651810-cd43-43d5-b2fd-77250378201e">

Привіт) Відкриваючи секцію 'Hero', зображення годинника залазять одне на одне. Можливо, це повʼязано з тим, що на початку шляху до зображень прописані дві крапки, на лекції нам розповідали, що шлях прописуємо суто між слешами)

2024-09-07 11:39 UTC, OlegSereda898 commented
виправив

2024-09-07 12:46 UTC, anakovalchuk requested changes
ще раз)

2024-09-07 12:46 UTC, anakovalchuk commented on src/partials/hero.html
> +        <div class="background-image"></div>
Div з класом background-image тут не потрібен. Як і стилі, котрі до нього застосовуються.

2024-09-07 12:46 UTC, anakovalchuk commented on src/css/hero.css
> +.background-image {
Ці стилі з класом .background-image не потрібні для реалізації секції Hero. Просто видали їх)

2024-09-07 12:46 UTC, anakovalchuk commented on src/css/hero.css
> +@media screen and (min-device-pixel-ratio: 2),
За рахунок цих медіа-правил, на секцію hero накладається додаткове зображення (як фонове). Їх також не потрібно додавати.

2024-09-07 12:46 UTC, anakovalchuk commented on src/css/hero.css
> +    .background-image {
Аналогічно до попередніх коментарів для мобільної версії.

2024-09-07 12:46 UTC, anakovalchuk commented on src/css/hero.css
> +    @media screen and (min-device-pixel-ratio: 2),
Аналогічно до попередніх коментарів для мобільної версії.

2024-09-07 12:46 UTC, anakovalchuk commented on src/css/hero.css
> +    @media screen and (min-device-pixel-ratio: 2),
Аналогічно до попередніх коментарів для мобільної версії.

2024-09-07 12:46 UTC, anakovalchuk commented on src/css/hero.css
> +    .background-image {
Аналогічно до попередніх коментарів для мобільної версії.

2024-09-07 12:46 UTC, anakovalchuk commented on src/css/hero.css
> +    .hero-text {
<img width="300" alt="Screenshot 2024-09-07 at 14 41 37" src="https://github.com/user-attachments/assets/5da55a66-a3ee-4bc3-98ce-1f2b4e69c606">

Параграф відрізняється на планшетній та десктопній версії від того, що є на макеті. Ширина описової частини (не заголовка, а параграфу) = 480px.

2024-09-08 08:57 UTC, OlegSereda898 commented on src/css/hero.css
> +    .hero-text {
Виправив здається повинно бути нормально

2024-09-08 11:43 UTC, anakovalchuk approved these changes
Well done!

2024-09-08 11:44 UTC, merged